// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package database

import (
	"context"
)

type Querier interface {
	CreateNote(ctx context.Context, arg CreateNoteParams) (Note, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteAccount(ctx context.Context, id int32) error
	DeleteAllNotes(ctx context.Context) error
	DeleteNote(ctx context.Context, id int32) error
	GetNote(ctx context.Context, id int32) (Note, error)
	ListNotes(ctx context.Context, arg ListNotesParams) ([]Note, error)
	UpdateAccount(ctx context.Context, arg UpdateAccountParams) (User, error)
	UpdateNote(ctx context.Context, arg UpdateNoteParams) (Note, error)
	UpdateNoteDescription(ctx context.Context, arg UpdateNoteDescriptionParams) (Note, error)
	UpdateNoteTitle(ctx context.Context, arg UpdateNoteTitleParams) (Note, error)
}

var _ Querier = (*Queries)(nil)
