// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v5.26.0
// source: service_legit_notes.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// LegitNotesClient is the client API for LegitNotes service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type LegitNotesClient interface {
	CreateUser(ctx context.Context, in *CreateUserRequest, opts ...grpc.CallOption) (*CreateUserResponse, error)
	LoginUser(ctx context.Context, in *LoginUserRequest, opts ...grpc.CallOption) (*LoginUserResponse, error)
}

type legitNotesClient struct {
	cc grpc.ClientConnInterface
}

func NewLegitNotesClient(cc grpc.ClientConnInterface) LegitNotesClient {
	return &legitNotesClient{cc}
}

func (c *legitNotesClient) CreateUser(ctx context.Context, in *CreateUserRequest, opts ...grpc.CallOption) (*CreateUserResponse, error) {
	out := new(CreateUserResponse)
	err := c.cc.Invoke(ctx, "/pb.LegitNotes/CreateUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *legitNotesClient) LoginUser(ctx context.Context, in *LoginUserRequest, opts ...grpc.CallOption) (*LoginUserResponse, error) {
	out := new(LoginUserResponse)
	err := c.cc.Invoke(ctx, "/pb.LegitNotes/LoginUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LegitNotesServer is the server API for LegitNotes service.
// All implementations must embed UnimplementedLegitNotesServer
// for forward compatibility
type LegitNotesServer interface {
	CreateUser(context.Context, *CreateUserRequest) (*CreateUserResponse, error)
	LoginUser(context.Context, *LoginUserRequest) (*LoginUserResponse, error)
	mustEmbedUnimplementedLegitNotesServer()
}

// UnimplementedLegitNotesServer must be embedded to have forward compatible implementations.
type UnimplementedLegitNotesServer struct {
}

func (UnimplementedLegitNotesServer) CreateUser(context.Context, *CreateUserRequest) (*CreateUserResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateUser not implemented")
}
func (UnimplementedLegitNotesServer) LoginUser(context.Context, *LoginUserRequest) (*LoginUserResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LoginUser not implemented")
}
func (UnimplementedLegitNotesServer) mustEmbedUnimplementedLegitNotesServer() {}

// UnsafeLegitNotesServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LegitNotesServer will
// result in compilation errors.
type UnsafeLegitNotesServer interface {
	mustEmbedUnimplementedLegitNotesServer()
}

func RegisterLegitNotesServer(s grpc.ServiceRegistrar, srv LegitNotesServer) {
	s.RegisterService(&LegitNotes_ServiceDesc, srv)
}

func _LegitNotes_CreateUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LegitNotesServer).CreateUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.LegitNotes/CreateUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LegitNotesServer).CreateUser(ctx, req.(*CreateUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LegitNotes_LoginUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LegitNotesServer).LoginUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.LegitNotes/LoginUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LegitNotesServer).LoginUser(ctx, req.(*LoginUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// LegitNotes_ServiceDesc is the grpc.ServiceDesc for LegitNotes service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var LegitNotes_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.LegitNotes",
	HandlerType: (*LegitNotesServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateUser",
			Handler:    _LegitNotes_CreateUser_Handler,
		},
		{
			MethodName: "LoginUser",
			Handler:    _LegitNotes_LoginUser_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "service_legit_notes.proto",
}
